spring.application.name=eduerp
server.port=${PORT:8080}

spring.datasource.url=mysql://root:iPjdjntWpyhLJvdjmarhGXBFkxhfhBlS?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=iPjdjntWpyhLJvdjmarhGXBFkxhfhBlS

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Execute data.sql after schema generation
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.mode=always
# spring.sql.init.data-locations=classpath:data.sql
